function [ ] = printAlgo( algoResults, evalNum, name )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

color = ['r' 'g' 'b'];

markerSize = 9;
LineWidth = 0.3;
offset = 0.8;
color = [[0,0.7,0.2]; [0.7,0,0.9]; [0.9, 0,0.2]];

errMax = max(max(cat(2, algoResults{:, [2 4]}), [], 2))

yMax = round(2*max(max(cat(2, algoResults{:, [1 3]}), [], 2)))/2 +1

yMin = floor(min(min(cat(2, algoResults{:, [1 3]}), [], 2)) - errMax)

%%%%%%%%%%%%%% BEST INDIVIDUAL %%%%%%%%%%%%%%
i = 1;
fig1 = figure
hold on;
hE =errorbar(evalNum, algoResults{1,1}, algoResults{1,2});

set(hE                            , ...
  'Color'           ,color(i, :)  , ...
  'LineStyle'       , '--'        , ...
  'LineWidth'       , LineWidth        , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , markerSize           , ...
  'MarkerEdgeColor' , 'k'  , ...
  'MarkerFaceColor' , color(i, :)  );


i = i+1;
evalNum = evalNum -offset;

hE =errorbar(evalNum, algoResults{2,1}, algoResults{2,2});

set(hE                            , ...
  'Color'           ,color(i, :)  , ...
  'LineStyle'       , ':', ...
  'LineWidth'       , LineWidth          , ...
  'Marker'          , 's'         , ...
  'MarkerSize'      , markerSize           , ...
  'MarkerEdgeColor' , 'k'  , ...
  'MarkerFaceColor' , color(i, :)  );

i = i+1;
evalNum = evalNum -offset;
hE =errorbar(evalNum, algoResults{3,1}, algoResults{3,2});

set(hE                            , ...
  'Color'           ,color(i, :)  , ...
  'LineStyle'       , '-.'        , ...
  'LineWidth'       , LineWidth        , ...
  'Marker'          , '^'         , ...
  'MarkerSize'      , markerSize           , ...
  'MarkerEdgeColor' , 'k'  , ...
  'MarkerFaceColor' , color(i, :)  );



legend('DE','GA', 'OptaiNet');
xlabel('Evaluations')
ylabel('MLE')
t = strcat(name, ' - Best Individual')
title(t)

hold off;
axis([0 inf yMin yMax])
print(fig1,t,'-dpng')

%%%%%%%%%%%%%% POP AVERAGE %%%%%%%%%%%%%%
i = 1;
fig2 = figure
hold on;
hE =errorbar(evalNum, algoResults{1,3}, algoResults{1,4});

set(hE                            , ...
  'Color'           ,color(i, :)  , ...
  'LineStyle'       , '--'        , ...
  'LineWidth'       , LineWidth        , ...
  'Marker'          , 'o'         , ...
  'MarkerSize'      , markerSize           , ...
  'MarkerEdgeColor' , 'k'  , ...
  'MarkerFaceColor' , color(i, :)  );


i = i+1;
evalNum = evalNum -offset;

hE =errorbar(evalNum, algoResults{2,3}, algoResults{2,4});

set(hE                            , ...
  'Color'           ,color(i, :)  , ...
  'LineStyle'       , ':', ...
  'LineWidth'       , LineWidth          , ...
  'Marker'          , 's'         , ...
  'MarkerSize'      , markerSize           , ...
  'MarkerEdgeColor' , 'k'  , ...
  'MarkerFaceColor' , color(i, :)  );

i = i+1;
evalNum = evalNum -offset;
hE =errorbar(evalNum, algoResults{3,3}, algoResults{3,4});

set(hE                            , ...
  'Color'           ,color(i, :)  , ...
  'LineStyle'       , '-.'        , ...
  'LineWidth'       , LineWidth        , ...
  'Marker'          , '^'         , ...
  'MarkerSize'      , markerSize           , ...
  'MarkerEdgeColor' , 'k'  , ...
  'MarkerFaceColor' , color(i, :)  );



legend('DE','GA', 'OptaiNet');
xlabel('Evaluations')
ylabel('MLE')

t = strcat(name, ' - Population Average')
title(t)

hold off;
axis([0 inf yMin yMax])
print(fig2,t,'-dpng')
end

